spring.application.name=backend
#TODO config - znalezc swoje ip uzywajac ipconfig lub ip
server.address=0.0.0.0
server.port=8080
# JWT Config
security.jwt.secret=${JWT_SECRET:FallbackSecretKeyRequiredMinimum256BitsToPreventIssuesUnderSpringSecurity!}
